// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdBuowLnaeL_v4tokOIDiocUt9XeszE3c',
    appId: '1:412484659377:web:987ecc102c12a3ce95da90',
    messagingSenderId: '412484659377',
    projectId: 'skill-swap-e0a49',
    authDomain: 'skill-swap-e0a49.firebaseapp.com',
    storageBucket: 'skill-swap-e0a49.firebasestorage.app',
    measurementId: 'G-74CM5LHEXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrCWtAu98oSq-UEG5j2nAMbWkZO8Z9W98',
    appId: '1:412484659377:android:775fe5a07eb9396f95da90',
    messagingSenderId: '412484659377',
    projectId: 'skill-swap-e0a49',
    storageBucket: 'skill-swap-e0a49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9t1vlW9NiCsG9iCKSOkS62m_VniwZBW4',
    appId: '1:412484659377:ios:0e6fcc728bae60ab95da90',
    messagingSenderId: '412484659377',
    projectId: 'skill-swap-e0a49',
    storageBucket: 'skill-swap-e0a49.firebasestorage.app',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9t1vlW9NiCsG9iCKSOkS62m_VniwZBW4',
    appId: '1:412484659377:ios:0e6fcc728bae60ab95da90',
    messagingSenderId: '412484659377',
    projectId: 'skill-swap-e0a49',
    storageBucket: 'skill-swap-e0a49.firebasestorage.app',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdBuowLnaeL_v4tokOIDiocUt9XeszE3c',
    appId: '1:412484659377:web:f300cffa647be8b795da90',
    messagingSenderId: '412484659377',
    projectId: 'skill-swap-e0a49',
    authDomain: 'skill-swap-e0a49.firebaseapp.com',
    storageBucket: 'skill-swap-e0a49.firebasestorage.app',
    measurementId: 'G-JGBX809MVZ',
  );
}
